// neighbors.js
// Land-border adjacency for ~195 countries (ISO 3166-1 alpha-3 codes).
// Each entry lists all countries sharing a land border (or a very short
// permanent water crossing treated as a border, e.g. Denmark–Sweden bridge).

const NEIGHBOR_DATA = {
  AFG: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
  ALB: ["MNE", "SRB", "MKD", "GRC"],
  DZA: ["MAR", "TUN", "LBY", "NER", "MLI", "MRT", "ESH"],
  AND: ["FRA", "ESP"],
  AGO: ["COD", "COG", "ZMB", "NAM"],
  ARG: ["CHL", "BOL", "PRY", "BRA", "URY"],
  ARM: ["TUR", "GEO", "AZE", "IRN"],
  AUT: ["DEU", "CZE", "SVK", "HUN", "SVN", "ITA", "CHE", "LIE"],
  AZE: ["RUS", "GEO", "ARM", "IRN", "TUR"],
  BHS: [],
  BHR: [],
  BGD: ["IND", "MMR"],
  BLR: ["RUS", "LVA", "LTU", "POL", "UKR"],
  BEL: ["FRA", "LUX", "DEU", "NLD"],
  BLZ: ["MEX", "GTM"],
  BEN: ["NER", "BFA", "TGO", "NGA"],
  BTN: ["CHN", "IND"],
  BOL: ["PER", "BRA", "PRY", "ARG", "CHL"],
  BIH: ["HRV", "SRB", "MNE"],
  BWA: ["ZAF", "ZWE", "NAM", "ZMB"],
  BRA: ["VEN", "GUY", "SUR", "COL", "PER", "BOL", "PRY", "ARG", "URY"],
  BRN: ["MYS"],
  BGR: ["ROU", "SRB", "MKD", "GRC", "TUR"],
  BFA: ["MLI", "NER", "BEN", "TGO", "GHA", "CIV"],
  BDI: ["COD", "RWA", "TZA"],
  CPV: [],
  KHM: ["THA", "LAO", "VNM"],
  CMR: ["NGA", "CAF", "COD", "COG", "GAB", "GNQ"],
  CAN: ["USA"],
  CAF: ["SDN", "SSD", "COD", "COG", "CMR", "NGA", "TCD"],
  TCD: ["LBY", "SDN", "CAF", "CMR", "NGA", "NER"],
  CHL: ["PER", "BOL", "ARG"],
  CHN: ["RUS", "MNG", "KAZ", "KGZ", "TJK", "AFG", "PAK", "IND", "NPL", "BTN", "MMR", "LAO", "VNM", "PRK"],
  COL: ["PAN", "VEN", "BRA", "PER", "ECU"],
  COM: [],
  COD: ["CAF", "SSD", "UGA", "RWA", "BDI", "TZA", "ZMB", "AGO", "COG"],
  COG: ["CAF", "CMR", "GAB", "AGO", "COD"],
  CRI: ["NIC", "PAN"],
  CIV: ["LBR", "GIN", "MLI", "BFA", "GHA"],
  HRV: ["SVN", "HUN", "SRB", "BIH", "MNE"],
  CUB: [],
  CYP: [],
  CZE: ["DEU", "POL", "SVK", "AUT"],
  DNK: ["DEU"],
  DJI: ["ERI", "ETH", "SOM"],
  DOM: ["HTI"],
  ECU: ["COL", "PER"],
  EGY: ["LBY", "SDN", "ISR", "PSE"],
  SLV: ["GTM", "HND"],
  GNQ: ["CMR", "GAB"],
  ERI: ["SDN", "ETH", "DJI"],
  EST: ["LVA", "RUS"],
  SWZ: ["ZAF", "MOZ"],
  ETH: ["ERI", "DJI", "SOM", "KEN", "SSD", "SDN"],
  FJI: [],
  FIN: ["NOR", "SWE", "RUS"],
  FRA: ["BEL", "LUX", "DEU", "CHE", "ITA", "MCO", "AND", "ESP"],
  GAB: ["CMR", "GNQ", "COG"],
  GMB: ["SEN"],
  GEO: ["RUS", "TUR", "ARM", "AZE"],
  DEU: ["DNK", "POL", "CZE", "AUT", "CHE", "FRA", "LUX", "BEL", "NLD"],
  GHA: ["CIV", "BFA", "TGO"],
  GRC: ["ALB", "MKD", "BGR", "TUR"],
  GTM: ["MEX", "BLZ", "HND", "SLV"],
  GIN: ["SEN", "GNB", "SLE", "LBR", "CIV", "MLI"],
  GNB: ["SEN", "GIN"],
  GUY: ["VEN", "BRA", "SUR"],
  HTI: ["DOM"],
  HND: ["GTM", "SLV", "NIC"],
  HUN: ["AUT", "SVK", "UKR", "ROU", "SRB", "HRV", "SVN"],
  ISL: [],
  IND: ["PAK", "CHN", "NPL", "BTN", "BGD", "MMR"],
  IDN: ["PNG", "TLS", "MYS"],
  IRN: ["IRQ", "TUR", "AZE", "ARM", "TKM", "AFG", "PAK"],
  IRQ: ["TUR", "SYR", "JOR", "SAU", "KWT", "IRN"],
  IRL: ["GBR"],
  ISR: ["LBN", "SYR", "JOR", "EGY", "PSE"],
  ITA: ["FRA", "CHE", "AUT", "SVN", "SMR", "VAT"],
  JAM: [],
  JPN: [],
  JOR: ["SYR", "IRQ", "SAU", "ISR", "PSE"],
  KAZ: ["RUS", "CHN", "KGZ", "UZB", "TKM"],
  KEN: ["ETH", "SOM", "TZA", "UGA", "SSD"],
  PRK: ["CHN", "RUS", "KOR"],
  KOR: ["PRK"],
  KWT: ["IRQ", "SAU"],
  KGZ: ["KAZ", "CHN", "TJK", "UZB"],
  LAO: ["CHN", "VNM", "KHM", "THA", "MMR"],
  LVA: ["EST", "RUS", "BLR", "LTU"],
  LBN: ["SYR", "ISR"],
  LSO: ["ZAF"],
  LBR: ["GIN", "SLE", "CIV"],
  LBY: ["TUN", "DZA", "NER", "TCD", "SDN", "EGY"],
  LIE: ["AUT", "CHE"],
  LTU: ["LVA", "BLR", "POL", "RUS"],
  LUX: ["BEL", "FRA", "DEU"],
  MDG: [],
  MWI: ["MOZ", "TZA", "ZMB"],
  MYS: ["THA", "IDN", "BRN"],
  MDV: [],
  MLI: ["DZA", "MRT", "SEN", "GIN", "CIV", "BFA", "NER"],
  MLT: [],
  MRT: ["DZA", "ESH", "SEN", "MLI"],
  MUS: [],
  MEX: ["USA", "GTM", "BLZ"],
  MDA: ["ROU", "UKR"],
  MCO: ["FRA"],
  MNG: ["RUS", "CHN"],
  MNE: ["HRV", "BIH", "SRB", "ALB"],
  MAR: ["DZA", "ESH", "ESP"],
  MOZ: ["TZA", "MWI", "ZMB", "ZWE", "ZAF", "SWZ"],
  MMR: ["CHN", "LAO", "THA", "BGD", "IND"],
  NAM: ["AGO", "ZMB", "BWA", "ZAF"],
  NPL: ["CHN", "IND"],
  NLD: ["BEL", "DEU"],
  NZL: [],
  NIC: ["HND", "CRI"],
  NER: ["DZA", "LBY", "TCD", "NGA", "BEN", "BFA", "MLI"],
  NGA: ["NER", "TCD", "CMR", "BEN"],
  MKD: ["SRB", "BGR", "GRC", "ALB"],
  NOR: ["SWE", "FIN", "RUS"],
  OMN: ["SAU", "YEM", "ARE"],
  PAK: ["IRN", "AFG", "CHN", "IND"],
  PAN: ["CRI", "COL"],
  PNG: ["IDN"],
  PRY: ["BOL", "ARG", "BRA"],
  PER: ["ECU", "COL", "BRA", "BOL", "CHL"],
  PHL: [],
  POL: ["DEU", "CZE", "SVK", "UKR", "BLR", "LTU", "RUS"],
  PRT: ["ESP"],
  QAT: ["SAU"],
  ROU: ["UKR", "MDA", "BGR", "SRB", "HUN"],
  RUS: ["NOR", "FIN", "EST", "LVA", "LTU", "POL", "BLR", "UKR", "GEO", "AZE", "KAZ", "MNG", "CHN", "PRK"],
  RWA: ["COD", "BDI", "TZA", "UGA"],
  SAU: ["JOR", "IRQ", "KWT", "QAT", "ARE", "OMN", "YEM"],
  SEN: ["MRT", "MLI", "GIN", "GNB", "GMB"],
  SRB: ["HUN", "ROU", "BGR", "MKD", "ALB", "MNE", "BIH", "HRV"],
  SLE: ["GIN", "LBR"],
  SGP: [],
  SVK: ["CZE", "POL", "UKR", "HUN", "AUT"],
  SVN: ["ITA", "AUT", "HUN", "HRV"],
  SOM: ["ETH", "KEN", "DJI"],
  ZAF: ["NAM", "BWA", "ZWE", "MOZ", "SWZ", "LSO"],
  SSD: ["SDN", "ETH", "KEN", "UGA", "COD", "CAF"],
  ESP: ["PRT", "FRA", "AND", "MAR"],
  LKA: [],
  SDN: ["EGY", "LBY", "TCD", "CAF", "SSD", "ETH", "ERI"],
  SUR: ["GUY", "BRA"],
  SWE: ["NOR", "FIN", "DNK"],
  CHE: ["DEU", "AUT", "LIE", "ITA", "FRA"],
  SYR: ["TUR", "IRQ", "JOR", "ISR", "LBN"],
  TWN: [],
  TJK: ["KGZ", "CHN", "AFG", "UZB"],
  TZA: ["KEN", "UGA", "RWA", "BDI", "COD", "ZMB", "MWI", "MOZ"],
  THA: ["MMR", "LAO", "KHM", "MYS"],
  TLS: ["IDN"],
  TGO: ["GHA", "BEN", "BFA"],
  TTO: [],
  TUN: ["DZA", "LBY"],
  TUR: ["GRC", "BGR", "GEO", "ARM", "AZE", "IRN", "IRQ", "SYR"],
  TKM: ["KAZ", "UZB", "AFG", "IRN"],
  UGA: ["SSD", "COD", "RWA", "TZA", "KEN"],
  UKR: ["RUS", "BLR", "POL", "SVK", "HUN", "ROU", "MDA"],
  ARE: ["SAU", "OMN"],
  GBR: ["IRL"],
  USA: ["CAN", "MEX"],
  URY: ["BRA", "ARG"],
  UZB: ["KAZ", "KGZ", "TJK", "AFG", "TKM"],
  VEN: ["COL", "BRA", "GUY"],
  VNM: ["CHN", "LAO", "KHM"],
  YEM: ["SAU", "OMN"],
  ZMB: ["COD", "TZA", "MWI", "MOZ", "ZWE", "BWA", "NAM", "AGO"],
  ZWE: ["ZAF", "MOZ", "ZMB", "BWA"],

  // ── Partial / observer states included for completeness ──────────────
  PSE: ["ISR", "EGY", "JOR"],   // Palestinian territories
  ESH: ["MAR", "DZA", "MRT"],   // Western Sahara
  SMR: ["ITA"],                  // San Marino
  VAT: ["ITA"],                  // Vatican City
  XKX: ["SRB", "MNE", "ALB", "MKD"],  // Kosovo
};
